// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DetailSeaction: typeof import('./src/components/detail-section/detail-seaction.vue')['default']
    DetailSeation: typeof import('./src/components/detail-section/detail-seation.vue')['default']
    DetailSection: typeof import('./src/components/detail-section/detail-section.vue')['default']
    HouseItemV3: typeof import('./src/components/house-item-v3/house-item-v3.vue')['default']
    HouseItemV9: typeof import('./src/components/house-item-v9/house-item-v9.vue')['default']
    Loading: typeof import('./src/components/loding/loading.vue')['default']
    Loding: typeof import('./src/components/loding/loding.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    'TabBar-自定义': typeof import('./src/components/tab-bar/tab-bar-自定义.vue')['default']
    TabControl: typeof import('./src/components/tab-control/tab-control.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
